language: node_js
node_js:
  - "10"
sudo: false

branches:
  only:
  - master

install:
  - sudo apt install xvfb
  - npm install -g @angular/cli

before_script:
  - cd instatech
  - npm install

cache:
  directories:
    - node_modules

script:
  - npm run lint
  - npm run build
  # - xvfb-run npm run e2e
  - ng build --prod

notifications:
  slack:
    rooms:
      - secure: "sdfusdhfsdofguhdfgubdsifgudfbgs3453durghssecurestringidsuag34522irueg=ltJpXZ5YTMJU2u0EjUA3ZYsB#08"
    on_success: always
